project:
  type: website
  output-dir: docs
website:
  title: "Maja Tech"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/manonja
      - icon: twitter
        href: https://twitter.com/muditaja
format:
  html:
    theme: cosmo
    css: styles.css
